### ISSUE TITLE
push.js should be a peerDependency

### ISSUE THREAD

**Issue by ncoden** [devotox/ember-cli-pushjs#23]
I think that `push.js` should be considered as a `peerDependencies`. Users expect `push.js` to be exposed and may want to customize its version.

> peerDependencies is for dependencies that are exposed to (and expected to be used by) the consuming code, as opposed to "private" dependencies that are not exposed, and are only an implementation detail.

See:
* https://stackoverflow.com/a/22004559/4317384
* https://stackoverflow.com/a/34645112/4317384

**Comment by ncoden** [comment]
Poke @devotox

**Comment by devotox** [comment]
It needs to be a dependency for ember cli node assets to roll it up @ncoden
