### ISSUE TITLE
Why is firebase a dependency? 

### ISSUE THREAD

**Issue by frsechet** [devotox/ember-cli-pushjs#26]
Hello,

I just saw this warning in the console:

```
It looks like you're using the development build of the Firebase JS SDK.
When deploying Firebase apps to production, it is advisable to only import
the individual SDK components you intend to use.

For the CDN builds, these are available in the following manner
(replace <PACKAGE> with the name of a component - i.e. auth, database, etc):

https://www.gstatic.com/firebasejs/5.0.0/firebase-<PACKAGE>.js
```

Which made me wonder: why would firebase (and related fcm package) be imported here, if [pushjs itself doesn't need it](https://github.com/Nickersoft/push.js/blob/master/package.json) and this is supposed to be a thin ember wrapper around it? Is there anything you need firebase for, and in that case, why is it not mentioned in the documentation?

Among other reasons I see not to include it:
- one more dependency to manage
- firebase belongs to Google which may not be everyone's cup of tea
- https://cost-of-modules.herokuapp.com/result?p=firebase@5.3.1

I just tried removing firebase completely and there doesn't seem to be any bug. Would you accept a PR that removes firebase completely?

**Comment by frsechet** [comment]
Hi @devotox,

did you get a chance to review #27 ?

It has been running in production on our stack for about a month now without any issue. Hope you can merge and release soon! How can I help?

**Comment by devotox** [comment]
Yes would love help maintaining. And I believe firebase is a dependency
since you can use the gcp push messaging with this addon

**Comment by frsechet** [comment]
Cool.

I would suggest making 2 different plugins then, because it does not fit the description (and most common need) of a `Simple Wrapper around Push JS`.

- one plugin is the wrapper around pushjs
- another plugin is built on top of this one for people who want to use firebase (and proposes a solution

Reasoning is that firebase is not the only provider of push notification that exists, while pushjs is "how" the notifications are technically displayed. If people want to integrate their own notification service, they can use the basic pushjs and add the service on top.

The cost of forcing firebase onto everyone is simply not worth it as it is not at all universal! 🙂

**Comment by devotox** [comment]
I think you are definitely correct.

I was using firebase heavily when I created this plugin but now I believe
it should be a lot more generic like you propose.

Are you able to make a pull request doing just this?

**Comment by frsechet** [comment]
How about that: https://github.com/devotox/ember-cli-pushjs/pull/27 🙂

**Comment by frsechet** [comment]
Thanks for the merge!

Don't forget to release to npm ;-) And let me know if you need further help!

**Comment by frsechet** [comment]
@devotox can you release to npm please?

**Comment by devotox** [comment]
Haaaa yes will do on the next few days

**Comment by devotox** [comment]
Released!
